dist: trusty
sudo: false
language: python
cache: pip
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - libgdal-dev
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=master
matrix:
  include:
    - python: 3.5
      env: TOXENV=lint
    - python: 3.3
      env: DJANGO=1.8
    - python: 3.6
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=master
  exclude:
    - python: 2.7
      env: DJANGO=master
    - python: pypy
      env: DJANGO=master
  allow_failures:
    - python: 3.4
      env: DJANGO=master
    - python: 3.5
      env: DJANGO=master
    - python: 3.6
      env: DJANGO=master
    - python: pypy
      env: DJANGO=master
install:
  - pip install tox-travis
before_script:
  # check gis
  - gdal-config --version
  - gdal-config --cflags
  - psql -U postgres -c "create extension postgis"
  # set up postgresql
  - psql -U postgres -c "create role cacheops login superuser"
  # postgis django backend requires these to exist
  - psql -U postgres -c "create database cacheops"
  - psql -U postgres -c "create database cacheops_slave"
  # mysql databases
  - mysql -e "create user cacheops"
  - mysql -u root -e "grant all on *.* to 'cacheops'@'localhost'"
  - mysql -e "create database cacheops"
  - mysql -e "create database cacheops_slave"
script:
  - GDAL_VERSION=1.10 tox
